# Generated by Django 6.0.4 on 2026-09-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': ('Категория',), 'verbose_name_plural': ('Категории',)},
        ),
    ]
